version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: beer_catalogue
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
volumes:
  pgdata: